import { TrendingUp, CheckSquare, Activity, Layers, Zap, ListChecks } from 'lucide-react';
import { Badge } from '@/components/ui/badge';

const STAT = (label, value, Icon, hint) => (
  <div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4">
    <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><Icon size={20} /></span>
    <div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="text-xl font-semibold text-slate-900">{value}</p>{hint && <p className="text-xs text-slate-500">{hint}</p>}</div>
  </div>
);

export default function CrmOverview({ version, active }) {
  const prov = version?.provenance || {};
  const sum = version?.summary || {};
  const counts = {
    stages: active?.stages?.length ?? version?.stage_count ?? 0,
    automations: active?.automations?.length ?? version?.automation_count ?? 0,
    tasks: active?.tasks?.length ?? version?.task_template_count ?? 0,
    rules: active?.scoreRules?.length ?? version?.score_rule_count ?? 0,
    widgets: active?.widgets?.length ?? version?.dashboard_widget_count ?? 0,
    reports: active?.reports?.length ?? version?.report_count ?? 0,
  };
  return (
    <div className="space-y-5">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-3">
        <div className="flex flex-col justify-between rounded-2xl border border-emerald-200 bg-emerald-50/40 p-5">
          <div><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">CRM Health Score</p><p className="mt-1 text-4xl font-bold text-emerald-900">{version?.health_score ?? '—'}<span className="text-lg text-emerald-600">/100</span></p></div>
          <p className="mt-2 text-sm text-emerald-800">{sum.industry || ''} · {sum.pipeline_name || ''}</p>
        </div>
        {STAT('Pipeline Stages', counts.stages, Layers, version?.status === 'approved' ? 'active' : version?.status)}
        {STAT('Scoring Rules', counts.rules, TrendingUp)}
        {STAT('Automations', counts.automations, Zap, 'definitions only')}
        {STAT('Task Templates', counts.tasks, ListChecks)}
        {STAT('Dashboard Widgets', counts.widgets, Activity)}
        {STAT('Reports', counts.reports, CheckSquare)}
      </div>
      <div className="grid gap-4 lg:grid-cols-3">
        <div className="rounded-2xl border border-slate-200 bg-white p-5">
          <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Lead Scoring Thresholds</p>
          <div className="mt-3 space-y-1.5 text-sm">
            {Object.entries(sum.thresholds || {}).map(([k, v]) => (
              <div key={k} className="flex items-center justify-between"><span className="capitalize text-slate-600">{k.replace('_', ' ')}</span><Badge variant="outline" className="font-mono">{String(v)}</Badge></div>
            ))}
          </div>
        </div>
        <div className="rounded-2xl border border-slate-200 bg-white p-5 lg:col-span-2">
          <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">AI Generation Metadata</p>
          <div className="mt-3 grid grid-cols-2 gap-x-6 gap-y-2 text-sm sm:grid-cols-3">
            <Meta label="Provider" value={prov.ai_provider} />
            <Meta label="Model" value={prov.ai_model} />
            <Meta label="Prompt" value={prov.prompt_version} />
            <Meta label="Generation time" value={`${((prov.token_usage?.llm_calls) || 0) ? Math.round((prov.generation_time_ms || 0) / 1000) : 0}s`} />
            <Meta label="LLM calls" value={prov.token_usage?.llm_calls} />
            <Meta label="Est. tokens" value={prov.token_usage?.estimated_tokens?.toLocaleString()} />
            <Meta label="Est. cost" value={`$${prov.estimated_cost}`} />
            <Meta label="Status" value={prov.generation_status} />
            <Meta label="Generated by" value={version?.generated_by} />
          </div>
        </div>
      </div>
    </div>
  );
}

function Meta({ label, value }) {
  return <div><p className="text-xs text-slate-400">{label}</p><p className="font-medium text-slate-800">{value || '—'}</p></div>;
}