import { useEffect, useMemo, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Activity, CheckCircle2, RefreshCw, ServerCog, TriangleAlert } from 'lucide-react';

export default function AdminEngineHealth() {
  const [providers,setProviders]=useState([]); const [attempts,setAttempts]=useState([]); const [loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true); const [p,a]=await Promise.allSettled([base44.entities.Provider.list('-updated_date',300),base44.entities.ExecutionAttempt.list('-created_date',300)]); setProviders(p.status==='fulfilled'&&Array.isArray(p.value)?p.value:[]); setAttempts(a.status==='fulfilled'&&Array.isArray(a.value)?a.value:[]); setLoading(false);};
  useEffect(()=>{load();},[]);
  const stats=useMemo(()=>{const enabled=providers.filter(p=>p.enabled); const unhealthy=enabled.filter(p=>['down','degraded'].includes(p.health_status)); const failed=attempts.filter(a=>a.status==='FAILED'); const running=attempts.filter(a=>['PENDING','RUNNING','RETRYING','WAITING'].includes(a.status)); const success=attempts.filter(a=>a.status==='SUCCEEDED'); return {enabled,unhealthy,failed,running,success};},[providers,attempts]);
  return <div className="px-5 py-6 sm:px-8 lg:px-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-orange-600">Reliability</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Engine & Provider Health</h1><p className="mt-2 text-sm text-slate-600">Execution reliability, provider health, latest tests and failure pressure.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700"><RefreshCw size={15} className={loading?'animate-spin':''}/>Refresh</button></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={ServerCog} label="Enabled providers" value={stats.enabled.length}/><Metric icon={TriangleAlert} label="Degraded / down" value={stats.unhealthy.length} bad={stats.unhealthy.length>0}/><Metric icon={Activity} label="In progress / waiting" value={stats.running.length}/><Metric icon={CheckCircle2} label="Succeeded attempts" value={stats.success.length}/></div>
  <div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[950px] text-sm"><thead className="bg-slate-50 text-left text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Provider / engine</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Lifecycle</th><th className="px-4 py-3">Health</th><th className="px-4 py-3">Last test</th><th className="px-4 py-3">Failures</th><th className="px-4 py-3">API access</th><th className="px-4 py-3">Production</th></tr></thead><tbody className="divide-y divide-slate-100">{providers.map(p=><tr key={p.id} className="hover:bg-slate-50"><td className="px-4 py-3"><p className="font-semibold text-slate-900">{p.display_name||p.name}</p><p className="text-xs text-slate-400">{p.key}</p></td><td className="px-4 py-3 text-slate-600">{p.provider_type||p.category}</td><td className="px-4 py-3 text-slate-600">{p.provider_lifecycle||p.status}</td><td className="px-4 py-3"><Badge value={p.health_status||'unknown'}/></td><td className="px-4 py-3 text-slate-500">{p.last_tested_at?new Date(p.last_tested_at).toLocaleString():'—'}</td><td className="px-4 py-3 font-semibold text-slate-700">{p.failure_count||0}</td><td className="px-4 py-3 text-slate-600">{p.our_api_access||'UNKNOWN'}</td><td className="px-4 py-3 text-slate-600">{p.production_available||p.environment||'UNKNOWN'}</td></tr>)}{!loading&&providers.length===0&&<tr><td colSpan={8} className="px-4 py-10 text-center text-slate-400">No provider health records found.</td></tr>}</tbody></table></div>
  <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-base font-bold text-slate-950">Recent execution failures</h2><div className="mt-3 space-y-2">{stats.failed.slice(0,10).map(a=><div key={a.id} className="rounded-xl border border-red-100 bg-red-50/40 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-slate-900">{a.operation} · {a.provider_key||'unknown provider'}</p><span className="text-xs font-semibold text-red-700">{a.error_category||'FAILED'}</span></div><p className="mt-1 text-xs text-slate-600">Case {String(a.case_id||'').slice(-8)} · {a.error_code||'no code'} · {a.error_message||'No error message'}</p></div>)}{stats.failed.length===0&&<p className="text-sm text-emerald-700">No failed execution attempts in the loaded window.</p>}</div></div></div>;
}
function Metric({icon:Icon,label,value,bad}) { return <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${bad?'bg-red-50 text-red-700':'bg-slate-50 text-slate-700'}`}><Icon size={17}/></div><p className="mt-3 text-2xl font-bold text-slate-950">{value}</p><p className="text-xs font-semibold text-slate-500">{label}</p></div>; }
function Badge({value}) { const v=String(value||'unknown').toLowerCase(); const cls=v==='healthy'?'bg-emerald-50 text-emerald-700':v==='down'?'bg-red-50 text-red-700':v==='degraded'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600'; return <span className={`rounded-full px-2 py-1 text-xs font-bold ${cls}`}>{v}</span>; }