import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { AlertOctagon, CircleDollarSign, Headset, RefreshCw, Wrench } from 'lucide-react';

const safeList = async (name, limit=300) => { try { const r=await base44.entities[name].list('-created_date',limit); return Array.isArray(r)?r:[]; } catch { return []; } };

export default function AdminFailures(){
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [filter,setFilter]=useState('ALL');
  const load=async()=>{setLoading(true); const [attempts,tasks,payments,tickets]=await Promise.all([safeList('ExecutionAttempt'),safeList('OperationsTask'),safeList('Payment'),safeList('SupportTicket')]); setData({attempts,tasks,payments,tickets}); setLoading(false);}; useEffect(()=>{load();},[]);
  const items=useMemo(()=>{if(!data)return[]; const rows=[]; data.attempts.filter(a=>['FAILED','RETRYING','WAITING'].includes(a.status)).forEach(a=>rows.push({id:`exec-${a.id}`,type:'EXECUTION',severity:a.status==='FAILED'?'CRITICAL':'HIGH',title:`${a.operation} · ${a.provider_key||'unknown provider'}`,detail:a.error_message||a.waiting_reason||a.error_code||a.status,caseId:a.case_id,at:a.completed_at||a.started_at||a.created_date})); data.tasks.filter(t=>t.status==='BLOCKED').forEach(t=>rows.push({id:`task-${t.id}`,type:'OPERATIONS',severity:t.priority==='URGENT'?'CRITICAL':'HIGH',title:t.title||t.task_type,detail:t.block_reason||'Operations task blocked',caseId:t.case_id,at:t.blocked_at||t.created_at})); data.payments.filter(p=>p.status==='FAILED').forEach(p=>rows.push({id:`pay-${p.id}`,type:'PAYMENT',severity:'HIGH',title:`Payment failed · ${p.provider_key||'provider'}`,detail:p.failure_code||p.failure_category||'Payment failure',caseId:p.application_id,at:p.created_date})); data.tickets.filter(t=>t.priority==='URGENT'&&!['RESOLVED','CLOSED'].includes(t.status)).forEach(t=>rows.push({id:`ticket-${t.id}`,type:'SUPPORT',severity:'HIGH',title:`${t.ticket_number} · ${t.subject||t.category}`,detail:`${t.status} · ${t.category}`,caseId:t.application_id,at:t.created_date})); return rows.sort((a,b)=>new Date(b.at||0)-new Date(a.at||0));},[data]);
  const shown=filter==='ALL'?items:items.filter(i=>i.type===filter);
  return <div className="px-5 py-6 sm:px-8 lg:px-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-orange-600">Exceptions</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Failures & Incidents</h1><p className="mt-2 text-sm text-slate-600">One triage view for execution failures, blocked operations, failed payments and urgent support.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700"><RefreshCw size={15} className={loading?'animate-spin':''}/>Refresh</button></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-4"><Metric icon={AlertOctagon} label="All incidents" value={items.length}/><Metric icon={Wrench} label="Execution / ops" value={items.filter(i=>['EXECUTION','OPERATIONS'].includes(i.type)).length}/><Metric icon={CircleDollarSign} label="Payments" value={items.filter(i=>i.type==='PAYMENT').length}/><Metric icon={Headset} label="Urgent support" value={items.filter(i=>i.type==='SUPPORT').length}/></div>
  <div className="mt-5 flex flex-wrap gap-2">{['ALL','EXECUTION','OPERATIONS','PAYMENT','SUPPORT'].map(k=><button key={k} onClick={()=>setFilter(k)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${filter===k?'bg-slate-950 text-white':'border border-slate-200 bg-white text-slate-600'}`}>{k}</button>)}</div>
  <div className="mt-4 space-y-2">{loading&&<div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-400">Loading incidents…</div>}{!loading&&shown.length===0&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center text-sm font-semibold text-emerald-700">No incidents in this view.</div>}{shown.map(i=><div key={i.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${i.severity==='CRITICAL'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{i.severity}</span><span className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{i.type}</span></div><h3 className="mt-2 text-sm font-bold text-slate-950">{i.title}</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-600">{i.detail}</p></div><div className="text-right"><p className="text-xs text-slate-400">{i.at?new Date(i.at).toLocaleString():'—'}</p>{i.caseId&&<Link to={`/admin/cases/${i.caseId}`} className="mt-2 inline-block text-xs font-bold text-orange-700 hover:underline">Open case</Link>}</div></div></div>)}</div></div>;
}
function Metric({icon:Icon,label,value}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><Icon size={17} className="text-slate-500"/><p className="mt-3 text-2xl font-bold text-slate-950">{value}</p><p className="text-xs font-semibold text-slate-500">{label}</p></div>}