// Human-authored starter Industry Blueprints for the catalog's most common
// verticals, plus fallbacks. Seeds the managed library on first run so the
// platform is immediately useful; `generate-blueprint` upgrades any industry
// to a full AI version on demand. New improvements always fork a new version.

const base = (industry_key: string, industry_label: string, category: string, extra: any) => ({
  tenant_id: "system", industry_key, industry_label, category,
  version: 1, status: "active", ai_generated: false, human_verified: true,
  last_updated: new Date().toISOString(), quality_score: 80, usage_count: 0, success_metrics: {},
  provenance: { source: "curated_seed" },
  business_model: extra.business_model,
  customer_personas: extra.customer_personas,
  typical_services: extra.typical_services,
  pricing_models: extra.pricing_models,
  sales_funnel: extra.sales_funnel,
  lead_sources: extra.lead_sources,
  website_structure: extra.website_structure,
  seo_strategy: extra.seo_strategy,
  crm_pipeline: extra.crm_pipeline,
  email_sequences: extra.email_sequences,
  marketing_calendar: extra.marketing_calendar,
  kpis: extra.kpis,
  compliance_reminders: extra.compliance_reminders || [],
  common_automations: extra.common_automations,
  typical_ai_employees: extra.typical_ai_employees,
  suggested_integrations: extra.suggested_integrations,
  business_risks: extra.business_risks,
  growth_strategies: extra.growth_strategies,
  expansion_strategies: extra.expansion_strategies,
});

export const CURATED: Record<string, any> = {
  gym: base("gym", "Gym / Fitness Center", "fitness", {
    business_model: "Monthly membership + personal training & class upsells; revenue scales with retention and referrals.",
    customer_personas: [
      { name: "The Beginner", description: "Sedentary adult starting fitness, wants guidance and a friendly first step.", needs: ["onboarding", "beginner classes", "no judgment"] },
      { name: "The Regular", description: "Trains 4-6x/week, values equipment variety and community.", needs: ["classes", "good gear", "community"] },
      { name: "The Goal-Setter", description: "Wants transformation, hires a personal trainer.", needs: ["PT packages", "progress tracking"] },
    ],
    typical_services: ["Monthly membership", "Quarterly/Annual membership", "Personal training", "Group classes (HIIT, Yoga, Zumba)", "Nutrition coaching", "Body composition assessment"],
    pricing_models: ["Free trial class", "Monthly ₹1500-3000", "Annual discounted", "PT packages (₹500-1500/session)", "Family/corporate plans"],
    sales_funnel: ["Free trial booking", "Tour + consultation", "Trial signup", "Membership conversion", "Upgrade to PT/classes", "Referral loop"],
    lead_sources: ["Google Maps (local SEO)", "Instagram Reels", "Referral (invite-a-friend)", "Corporate wellness tie-ups", "Class booking ads"],
    website_structure: [
      { title: "Home", purpose: "Hero + class schedule teaser + CTA book trial" },
      { title: "Classes", purpose: "Weekly schedule + instructor bios + book" },
      { title: "Membership", purpose: "Plans + pricing + join" },
      { title: "Personal Training", purpose: "Packages + trainer bios" },
      { title: "About", purpose: "Coaches + facility gallery" },
      { title: "Blog", purpose: "Fitness tips driving SEO" },
      { title: "Contact", purpose: "Location + trial booking form" },
    ],
    seo_strategy: { primary_keywords: ["gym in {city}", "fitness center {city}", "best gym near me"], content_pillars: ["Workout routines", "Nutrition", "Member transformations", "Class previews"], location_strategy: "City + neighbourhood landing pages" },
    crm_pipeline: { stages: ["Trial booked", "Tour done", "Trial attended", "Member", "Upgraded", "Churned"], lead_sources: ["Website form", "Instagram DM", "Walk-in", "Referral"] },
    email_sequences: [
      { name: "Trial follow-up", purpose: "Convert trial → member (3 emails over 5 days)" },
      { name: "Welcome series", purpose: "Onboard new member + upsell PT" },
      { name: "Win-back", purpose: "Reactivate cancelled members at 30/60 days" },
    ],
    marketing_calendar: [
      { month: "Jan", focus: "New Year resolutions — join campaigns" },
      { month: "Mar", focus: "Summer body freestyle launch" },
      { month: "Jun", focus: "Referral drive — bring a friend free" },
      { month: "Sep", focus: "Festive fitness — back to routine" },
      { month: "Dec", focus: "Annual membership discount + gifting" },
    ],
    kpis: ["Trial→member conversion %", "Monthly recurring revenue", "Churn rate", "Avg member LTV", "Class utilization"],
    compliance_reminders: ["Trainer certifications current", "Hygiene & equipment safety audits", "EMS/AED on-site"],
    common_automations: ["Auto trial-booking confirmations", "Class reminders 1h before", "Membership renewal reminders", "Birthday + milestone messages", "Churn-risk flagging (no check-in 14d)"],
    typical_ai_employees: ["CMO (growth/marketing)", "Sales (membership conversion)", "Operations (scheduling/retention)", "Support (member queries)"],
    suggested_integrations: ["Class scheduling (Mindbody/Swim)", "Payments (Stripe/Razorpay)", "Instagram lead capture", "WhatsApp reminders"],
    business_risks: ["High churn from poor onboarding", "Seasonal dips", "Trainer attrition", "Equipment maintenance downtime"],
    growth_strategies: ["Launch referral program (bring-a-friend)", "Corporate wellness B2B packages", "Add nutrition coaching upsell", "Run transformation challenges"],
    expansion_strategies: ["Open second location in adjacent neighbourhood", "Franchise model", "Launch hybrid online classes app", "Partner with corporates for wellness"],
  }),

  restaurant: base("restaurant", "Restaurant", "food", {
    business_model: "Dine-in + takeaway/delivery; revenue from covers, average ticket, and repeat bookings.",
    customer_personas: [
      { name: "The Couple", description: "Date-night diners, value ambiance + reviews.", needs: ["reservation ease", "ambiance", "photo-worthy dishes"] },
      { name: "The Family", description: "Weekend family group, wants variety + kids options.", needs: ["family menu", "fast seating", "value combos"] },
      { name: "The Takeaway Regular", description: "Orders delivery weekly, values speed + consistency.", needs: ["easy ordering", "loyalty", "fast delivery"] },
    ],
    typical_services: ["Dine-in", "Takeaway", "Online delivery", "Reservation", "Private dining/events", "Catering"],
    pricing_models: ["A la carte", "Fixed thali/combo", "Loyalty points", "Happy-hour pricing", "Group/family combos"],
    sales_funnel: ["Discover on Google/Instagram", "View menu online", "Reserve or order", "Dine/order", "Loyalty signup", "Review + revisit"],
    lead_sources: ["Google Maps", "Instagram/Zomato/Swiggy", "Reviews", "Walk-by signage", "Loyalty referrals"],
    website_structure: [
      { title: "Home", purpose: "Hero dish + reserve CTA" },
      { title: "Menu", purpose: "Full menu + photos + online order" },
      { title: "Reservations", purpose: "Date/time/party-size booking" },
      { title: "Gallery", purpose: "Dish + interior photos" },
      { title: "Private Dining/Events", purpose: "Inquiry form" },
      { title: "Contact", purpose: "Hours, map, phone" },
    ],
    seo_strategy: { primary_keywords: ["{cuisine} restaurant in {city}", "best {cuisine} near me", "{city}delivery {cuisine}"], content_pillars: ["Signature dishes", "Chef stories", "Festivals/cuisines", "Pairings"], location_strategy: "Neighbourhood + cuisine landing pages" },
    crm_pipeline: { stages: ["Inquiry/Reservation", "First visit", "Repeat", "Regular", "Loyalty member"], lead_sources: ["Reservation", "Online order", "Review", "Walk-in"] },
    email_sequences: [
      { name: "Reservation confirm", purpose: "Confirm + prep + menu highlight" },
      { name: "Post-visit", purpose: "Review request + loyalty signup" },
      { name: "Loyalty monthly", purpose: "Offers + new dishes + events" },
    ],
    marketing_calendar: [
      { month: "Festivals", focus: "Festival-specific menus + combos" },
      { month: "Valentine/Fests", focus: "Couples/celebration set menus" },
      { month: "Monsoon", focus: "Comfort-food promos" },
      { month: "Dec", focus: "New Year parties + gift cards" },
    ],
    kpis: ["Covers per day", "Average ticket size", "Repeat visit %", "Delivery rating", "Loyalty members"],
    compliance_reminders: ["FSSAI license renewal", "Food safety / hygiene audits", "Fire & liquor license (if applicable)"],
    common_automations: ["Reservation confirmations + reminders", "Post-visit review request", "Loyalty point accrual", "Slow-day promo push", "Inventory reorder alerts"],
    typical_ai_employees: ["CMO (marketing/loyalty)", "Operations (reservations/inventory)", "Support (customer reviews)", "Sales (private dining/events)"],
    suggested_integrations: ["Reservations (Dineout/EazyDiner)", "Delivery (Zomato/Swiggy + own)", "Payments", "Instagram ordering"],
    business_risks: ["Spoilage/wastage", "Negative reviews going viral", "Staff shortages", "Food safety incidents"],
    growth_strategies: ["Launch loyalty + referral", "Add catering & private dining", "Pop-up/thali combos", "Festival menus & pre-orders"],
    expansion_strategies: ["Second outlet in high-footfall area", "Cloud kitchen for delivery-only brand", "Franchise the signature concept", "Bottled sauces/meal kits retail"],
  }),

  dentist: base("dentist", "Dentist", "healthcare", {
    business_model: "Fee-for-service + insurance/panel; revenue from recurring checkups + high-value procedures.",
    customer_personas: [
      { name: "The Anxious Patient", description: "Fears pain, needs reassurance and gentle care.", needs: ["trust", "painless promise", "clear cost"] },
      { name: "The Family", description: "Parents booking for kids + themselves.", needs: ["convenient scheduling", "pediatric care", "reminders"] },
      { name: "The Cosmetic Seeker", description: "Wants whitening/aligners, driven by aesthetics.", needs: ["before/after", "financing", "consultation"] },
    ],
    typical_services: ["Cleaning/checkup", "Cavity fillings", "Root canal", "Braces/aligners", "Whitening", "Implants", "Pediatric dentistry"],
    pricing_models: ["Per procedure", "Annual checkup plan", "Insurance panels", "EMI for high-value treatments"],
    sales_funnel: ["Symptom/Google search", "Book consult", "Consult + diagnosis", "Treatment plan + quote", "Treatment", "Recall 6 months"],
    lead_sources: ["Google (local SEO)", "Insurance panels", "Referrals", "Reviews", "Dental directories"],
    website_structure: [
      { title: "Home", purpose: "Trust + book appointment CTA" },
      { title: "Services", purpose: "Treatments + before/after" },
      { title: "Smile Gallery", purpose: "Cosmetic results" },
      { title: "For Families", purpose: "Pediatric + comfort care" },
      { title: "Pricing/Insurance", purpose: "Transparency + EMI" },
      { title: "Contact/Book", purpose: "Appointment form + map" },
    ],
    seo_strategy: { primary_keywords: ["dentist in {city}", "root canal {city}", "teeth whitening near me", "kids dentist {city}"], content_pillars: ["Oral hygiene tips", "Treatment explainers", "Myths", "Kids dental care"], location_strategy: "City + clinic-area landing pages" },
    crm_pipeline: { stages: ["Inquiry", "Consultation booked", "Consulted", "Treatment planned", "In treatment", "Completed", "Recall due"], lead_sources: ["Website form", "Phone", "Referral", "Insurance"] },
    email_sequences: [
      { name: "Appointment confirm", purpose: "Confirm + prep instructions" },
      { name: "Post-treatment care", purpose: "Aftercare + review request" },
      { name: "Recall", purpose: "6-month checkup reminder" },
    ],
    marketing_calendar: [
      { month: "Feb", focus: "Valentine smile whitening promo" },
      { month: "Apr", focus: "Oral health month — free checkup camps" },
      { month: "Aug", focus: "Back-to-school kids dental" },
      { month: "Dec", focus: "Use insurance benefits before year-end" },
    ],
    kpis: ["New patients/month", "Consult→treatment conversion", "Treatment acceptance $", "Recall compliance %", "Reviews/rating"],
    compliance_reminders: ["Dental council registration", "Sterilization protocol audits", "X-ray equipment calibration", "KSRA/medical waste disposal"],
    common_automations: ["Appointment confirmations + reminders", "Recall scheduling", "Post-treatment review requests", "Treatment plan EMI quotes", "Birthday greetings"],
    typical_ai_employees: ["CMO", "Sales (treatment acceptance)", "Operations (scheduling)", "Support (patient queries)"],
    suggested_integrations: ["Appointment scheduling", "Payments + EMI", "Insurance verification", "Reviews (Google)"],
    business_risks: ["Low treatment acceptance", "No-shows", "Negative reviews", "Compliance lapse"],
    growth_strategies: ["Free checkup camps for leads", "Aligner/whitening package promos", "Family recall automation", "Cosmetic treatment financing"],
    expansion_strategies: ["Second clinic in nearby city", "Specialty (implants/aligners) centre", "Tie up with corporates for dental benefits", "Teledentistry consults"],
  }),

  salon: base("salon", "Salon", "beauty", {
    business_model: "Appointment-based services + product retail; revenue from repeat visits + packages.",
    customer_personas: [
      { name: "The Bridal Client", description: "One big event, high spend, value results + trust.", needs: ["trials", "packages", "premium experience"] },
      { name: "The Regular", description: "Monthly grooming, wants loyalty + convenient booking.", needs: ["easy rebooking", "loyalty", "same stylist"] },
      { name: "The Trend-Seeker", description: "Follows trends, books new services.", needs: ["trend services", "instagram-worthy results"] },
    ],
    typical_services: ["Haircut & styling", "Colour & treatments", "Facials", "Waxing & threading", "Manicure/pedicure", "Bridal makeup", "Spa"],
    pricing_models: ["Per service", "Membership packages", "Bridal package", "Festive offers", "Product retail"],
    sales_funnel: ["Instagram/Google discover", "Book appointment", "Service", "Retail upsell", "Loyalty/member", "Rebook"],
    lead_sources: ["Instagram", "Google Maps", "Referrals", "Walk-ins", "Influencer collabs"],
    website_structure: [
      { title: "Home", purpose: "Lookbook + book CTA" },
      { title: "Services", purpose: "Services + price list" },
      { title: "Bridal", purpose: "Packages + trials + gallery" },
      { title: "Gallery", purpose: "Before/after + trends" },
      { title: "Membership", purpose: "Loyalty plans + join" },
      { title: "Contact", purpose: "Locations + book" },
    ],
    seo_strategy: { primary_keywords: ["salon in {city}", "best hair salon near me", "bridal makeup {city}", "facial near me"], content_pillars: ["Haircare tips", "Skincare routines", "Bridal looks", "Trends"], location_strategy: "City + neighbourhood pages" },
    crm_pipeline: { stages: ["Inquiry", "Booked", "First service", "Repeat", "Loyalty member"], lead_sources: ["Website booking", "Instagram DM", "Walk-in", "Referral"] },
    email_sequences: [
      { name: "Appointment confirm", purpose: "Confirm + prep" },
      { name: "Rebook reminder", purpose: "Trigger at service interval (4-6 weeks)" },
      { name: "Loyalty offers", purpose: "Member-only festive offers" },
    ],
    marketing_calendar: [
      { month: "Jan", focus: "New year new look" },
      { month: "May", focus: "Summer haircare/facials" },
      { month: "Oct", focus: "Festive + bridal season" },
      { month: "Dec", focus: "Party looks + gift cards" },
    ],
    kpis: ["Bookings/week", "Repeat rate", "Avg ticket + retail attach", "Loyalty members", "No-show rate"],
    compliance_reminders: ["Cosmetology licenses", "Hygiene & tool sterilisation", "Product expiry checks"],
    common_automations: ["Appointment confirmations + reminders", "Rebook at interval", "Loyalty point accrual", "Birthday offers", "Festive promos"],
    typical_ai_employees: ["CMO (growth/content)", "Operations (scheduling)", "Support (booking queries)", "Sales (member conversion)"],
    suggested_integrations: ["Booking (Fresha/own)", "Payments", "Instagram lead capture", "WhatsApp reminders"],
    business_risks: ["No-shows", "Trend cycle churn", "Product wastage", "Stylist attrition"],
    growth_strategies: ["Loyalty + membership program", "Bridal package premiumisation", "Influencer collabs", "Retail product push"],
    expansion_strategies: ["Second branch in nearby area", "Add spa/skin clinic vertical", "Franchise model", "D2C product line"],
  }),
};

export function curatedKeys(): string[] { return Object.keys(CURATED); }

export function curatedBlueprint(key: string): any | null { return CURATED[key] || null; }

// Minimal fallback if AI generation fails for a requested industry.
export function curatedFallback(key: string): any | null {
  return CURATED[key] ? {
    business_model: CURATED[key].business_model,
    customer_personas: CURATED[key].customer_personas,
    typical_services: CURATED[key].typical_services,
    pricing_models: CURATED[key].pricing_models,
    sales_funnel: CURATED[key].sales_funnel,
    lead_sources: CURATED[key].lead_sources,
    website_structure: CURATED[key].website_structure,
    seo_strategy: CURATED[key].seo_strategy,
    crm_pipeline: CURATED[key].crm_pipeline,
    email_sequences: CURATED[key].email_sequences,
    marketing_calendar: CURATED[key].marketing_calendar,
    kpis: CURATED[key].kpis,
    compliance_reminders: CURATED[key].compliance_reminders,
    common_automations: CURATED[key].common_automations,
    typical_ai_employees: CURATED[key].typical_ai_employees,
    suggested_integrations: CURATED[key].suggested_integrations,
    business_risks: CURATED[key].business_risks,
    growth_strategies: CURATED[key].growth_strategies,
    expansion_strategies: CURATED[key].expansion_strategies,
  } : null;
}